"""
train_path_B.py  —  Path B: Two-stage detect + classify pipeline.

Stage 1: YOLO detector (reuses best Path A weights) — localises objects
Stage 2: Crop classifier (ResNet-50 or ViT-B/16) — refines class prediction

Two crop-sourcing modes:
  --use_yolo_crops   Run the YOLO detector on every image and classify the
                     detected boxes (true apples-to-apples comparison with
                     evaluate_path_B_combined.py).  Crops are cached to
                     --crop_cache_dir on first run.
  (default)          Load the 224x224 GT crops pre-generated by preprocess.py
                     (faster, but uses ground-truth boxes, not detected ones).

Usage — YOLO-crop mode (recommended, matches evaluation protocol):
  conda activate litter_AB
  python train_path_B.py \
      --detector_weights ~/runs/path_A_5cls/yolov11m_o2o/weights/best.pt \
      --crops_dir        ~/processed_5cls \
      --output           ~/runs/path_B \
      --classifiers      resnet50 vit_b16_scratch vit_b16_imagenet \
      --epochs           50 \
      --batch            32 \
      --device           0 \
      --use_yolo_crops \
      --det_conf         0.25 \
      --crop_cache_dir   ~/runs/path_B/crop_cache

Usage — GT-crop mode (fast baseline):
  python train_path_B.py \
      --detector_weights ~/runs/path_A_5cls/yolov11m_o2o/weights/best.pt \
      --crops_dir        ~/processed_5cls \
      --output           ~/runs/path_B \
      --classifiers      resnet50 vit_b16_scratch vit_b16_imagenet \
      --epochs           50 --batch 32 --device 0
"""

import argparse
import json
import time
from pathlib import Path

import mlflow
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
import yaml
from PIL import Image
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms
from torchvision.io import read_image
from tqdm import tqdm
import timm
from sklearn.metrics import (
    precision_score, recall_score, f1_score,
    average_precision_score, confusion_matrix,
)
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay
from ensemble_boxes import weighted_boxes_fusion

# ─────────────────────────────────────────────────────────────────────────────
# CONSTANTS
# ─────────────────────────────────────────────────────────────────────────────

COARSE_CLASSES = ["plastic", "paper", "metal", "glass", "other"]
NUM_CLASSES    = len(COARSE_CLASSES)
CROP_SIZE      = 224
ENSEMBLE_AVAILABLE = True


CLASSIFIER_REGISTRY = {
    # B1: ResNet-50 — strong ImageNet CNN baseline
    "resnet50":         ("resnet50.a1_in1k",                          True),
    # B2: ViT-B/16 random init — architecture value without pretraining
    "vit_b16_scratch":  ("vit_base_patch16_224",                      False),
    # B3: ViT-B/16 ImageNet21k pretrained — large-scale pretraining value
    "vit_b16_imagenet": ("vit_base_patch16_224.augreg_in21k_ft_in1k", True),
    # B4: ViT-L/16 ImageNet21k pretrained — larger model with large-scale pretraining
    "vit_l16_imagenet":  ("vit_large_patch16_224.augreg_in21k_ft_in1k", True),
}

def _predict_array_yolo(model, img_pil: Image.Image, device, imgsz: int,
                        conf: float = 0.001, iou: float = 0.6):
    """
    Runs YOLO on a PIL image.
    Returns normalized boxes [x1,y1,x2,y2] in [0,1], scores, classes.
    """
    result = model.predict(
        source=img_pil,
        conf=conf,
        iou=iou,
        imgsz=imgsz,
        device=device,
        verbose=False,
    )[0]

    if result.boxes is not None and len(result.boxes):
        boxes = result.boxes.xyxyn.cpu().numpy().astype(np.float32)
        scores = result.boxes.conf.cpu().numpy().astype(np.float32)
        classes = result.boxes.cls.cpu().numpy().astype(int)
    else:
        boxes = np.zeros((0, 4), dtype=np.float32)
        scores = np.zeros((0,), dtype=np.float32)
        classes = np.zeros((0,), dtype=int)

    return boxes, scores, classes


def _undo_hflip_boxes_norm(boxes_norm: np.ndarray) -> np.ndarray:
    """
    Undo horizontal flip for normalized xyxy boxes in [0,1].
    """
    if len(boxes_norm) == 0:
        return boxes_norm

    out = boxes_norm.copy()
    out[:, 0] = 1.0 - boxes_norm[:, 2]
    out[:, 2] = 1.0 - boxes_norm[:, 0]
    return out


def predict_tta_wbf_yolo(
    model,
    img_pil: Image.Image,
    device,
    scales=(512, 640, 768),
    use_hflip=True,
    wbf_iou=0.55,
    skip_box_thr=0.001,
    det_iou=0.6,
):
    """
    Multi-scale TTA + optional horizontal flip, fused with Weighted Boxes Fusion.
    This mirrors the Path A TTA/WBF evaluation protocol.
    Returns pixel-coordinate xyxy boxes, scores, classes.
    """
    if not ENSEMBLE_AVAILABLE:
        raise RuntimeError(
            "TTA+WBF requested but ensemble_boxes is not installed. "
            "Install with: pip install ensemble-boxes"
        )

    W, H = img_pil.size

    boxes_list = []
    scores_list = []
    labels_list = []

    for scale in scales:
        boxes, scores, classes = _predict_array_yolo(
            model=model,
            img_pil=img_pil,
            device=device,
            imgsz=scale,
            conf=skip_box_thr,
            iou=det_iou,
        )
        boxes_list.append(boxes.tolist())
        scores_list.append(scores.tolist())
        labels_list.append(classes.tolist())

        if use_hflip:
            img_flip = img_pil.transpose(Image.FLIP_LEFT_RIGHT)

            boxes_f, scores_f, classes_f = _predict_array_yolo(
                model=model,
                img_pil=img_flip,
                device=device,
                imgsz=scale,
                conf=skip_box_thr,
                iou=det_iou,
            )

            boxes_f = _undo_hflip_boxes_norm(boxes_f)

            boxes_list.append(boxes_f.tolist())
            scores_list.append(scores_f.tolist())
            labels_list.append(classes_f.tolist())

    fused_boxes, fused_scores, fused_labels = weighted_boxes_fusion(
        boxes_list,
        scores_list,
        labels_list,
        weights=[1.0] * len(boxes_list),
        iou_thr=wbf_iou,
        skip_box_thr=skip_box_thr,
    )

    if len(fused_boxes) == 0:
        return (
            np.zeros((0, 4), dtype=np.float32),
            np.zeros((0,), dtype=np.float32),
            np.zeros((0,), dtype=int),
        )

    fused_boxes = np.array(fused_boxes, dtype=np.float32)
    fused_scores = np.array(fused_scores, dtype=np.float32)
    fused_labels = np.array(fused_labels, dtype=int)

    # normalized xyxy -> pixel xyxy
    boxes_px = fused_boxes.copy()
    boxes_px[:, [0, 2]] *= W
    boxes_px[:, [1, 3]] *= H

    boxes_px[:, [0, 2]] = np.clip(boxes_px[:, [0, 2]], 0, W)
    boxes_px[:, [1, 3]] = np.clip(boxes_px[:, [1, 3]], 0, H)

    return boxes_px, fused_scores, fused_labels

# ─────────────────────────────────────────────────────────────────────────────
# YOLO-CROP DATASET
# Extracts 224×224 crops from detected YOLO boxes rather than GT boxes.
# Matches the evaluation protocol used in evaluate_path_B_combined.py.
# ─────────────────────────────────────────────────────────────────────────────

class YOLOCropDataset(Dataset):
    """
    Runs a frozen YOLO detector over every image in {split}/path_B/images,
    matches each detected box to the nearest GT box (IoU ≥ 0.5) to assign a
    label, crops and resizes to 224×224, then caches to disk.

    On subsequent epochs the cached crops are loaded directly (fast path).

    Args:
        data_root:  processed dataset root (contains train/val/test/path_B)
        split:      "train" | "val" | "test"
        detector:   Ultralytics YOLO model (frozen, for inference only)
        device:     inference device string, e.g. "0" or "cpu"
        conf:       YOLO detection confidence threshold (default 0.25)
        transform:  torchvision transform applied after crop
        cache_dir:  if provided, crops are saved here and reloaded on re-use
    """

    def __init__(
        self,
        data_root: Path,
        split:     str,
        detector,
        device:    str,
        conf:      float = 0.25,
        transform=None,
        cache_dir: Path = None,
        use_tta_wbf: bool = False,
        tta_scales=(512, 640, 768),
        tta_flip: bool = False,
        tta_wbf_iou: float = 0.55,
        tta_skip_box_thr: float = 0.001,
    ):
        self.transform = transform
        self.samples   = []          # [(crop_tensor_or_path, label)]
        self._use_cache = cache_dir is not None
        self.use_tta_wbf = use_tta_wbf
        self.tta_scales = tuple(tta_scales)
        self.tta_flip = tta_flip
        self.tta_wbf_iou = tta_wbf_iou
        self.tta_skip_box_thr = tta_skip_box_thr

        img_dir = Path(data_root) / split / "path_B" / "images"
        lbl_dir = Path(data_root) / split / "path_B" / "labels"
        assert img_dir.exists(), f"Image dir not found: {img_dir}"

        cache_root = Path(cache_dir) / split if cache_dir else None
        if cache_root and cache_root.exists():
            # ── fast path: load from cache ────────────────────────────────
            print(f"  [{split}] Loading YOLOCropDataset from cache: {cache_root}")
            for cls_dir in sorted(cache_root.iterdir()):
                if not cls_dir.is_dir():
                    continue
                try:
                    cls_idx = int(cls_dir.name)
                except ValueError:
                    continue
                for p in cls_dir.glob("*.jpg"):
                    self.samples.append((p, cls_idx))
            print(f"  [{split}] {len(self.samples)} cached crops loaded")
            return

        # ── slow path: detect + crop + (optionally cache) ─────────────────
        print(f"\n  [{split}] Building YOLOCropDataset via YOLO detection…")
        img_paths = sorted(img_dir.glob("*.jpg"))
        n_matched = 0
        n_skipped = 0

        if cache_root:
            cache_root.mkdir(parents=True, exist_ok=True)

        for img_path in tqdm(img_paths, desc=f"  [{split}] YOLO crops"):
            lbl_path = lbl_dir / img_path.with_suffix(".txt").name

            # load GT boxes + labels from YOLO txt
            gt_boxes, gt_classes = [], []
            if lbl_path.exists():
                img_pil = Image.open(img_path)
                W, H    = img_pil.size
                for line in lbl_path.read_text().strip().splitlines():
                    parts = line.split()
                    if len(parts) < 5:
                        continue
                    cls_id      = int(parts[0])
                    cx,cy,nw,nh = map(float, parts[1:5])
                    x1=(cx-nw/2)*W; y1=(cy-nh/2)*H
                    x2=(cx+nw/2)*W; y2=(cy+nh/2)*H
                    gt_boxes.append([x1,y1,x2,y2])
                    gt_classes.append(cls_id)
            else:
                img_pil = None

            if not gt_boxes:
                n_skipped += 1
                continue

            if self.use_tta_wbf:
                det_boxes, det_scores, det_classes = predict_tta_wbf_yolo(
                    model=detector,
                    img_pil=img_pil,
                    device=device,
                    scales=self.tta_scales,
                    use_hflip=self.tta_flip,
                    wbf_iou=self.tta_wbf_iou,
                    skip_box_thr=self.tta_skip_box_thr,
                    det_iou=0.6,
                )

                keep = det_scores >= conf
                det_boxes = det_boxes[keep]

            else:
                result = detector.predict(
                    str(img_path),
                    conf=conf,
                    iou=0.6,
                    device=device,
                    verbose=False,
                )[0]

                if result.boxes is None or len(result.boxes) == 0:
                    n_skipped += 1
                    continue

                det_boxes = result.boxes.xyxy.cpu().numpy()

            if len(det_boxes) == 0:
                n_skipped += 1
                continue

            gt_arr = np.array(gt_boxes, dtype=np.float32)
            gt_cls = np.array(gt_classes, dtype=int)

            # match each detected box → GT box via IoU
            iou_mat = _box_iou_np(det_boxes, gt_arr)   # (N_det, N_gt)
            matched_gt = set()

            order = np.argsort(-det_boxes[:, 2] * det_boxes[:, 3])  # large first
            for det_idx in order:
                best_gt    = int(np.argmax(iou_mat[det_idx]))
                best_iou   = float(iou_mat[det_idx, best_gt])
                if best_iou < 0.5 or best_gt in matched_gt:
                    continue
                matched_gt.add(best_gt)
                label = int(gt_cls[best_gt])

                # crop + resize
                x1,y1,x2,y2 = det_boxes[det_idx].astype(int)
                W2, H2 = img_pil.size
                x1=max(0,x1); y1=max(0,y1)
                x2=min(W2,x2); y2=min(H2,y2)
                if x2<=x1 or y2<=y1:
                    continue
                crop = img_pil.crop((x1,y1,x2,y2)).convert("RGB")
                crop = crop.resize((CROP_SIZE, CROP_SIZE), Image.BILINEAR)

                if cache_root:
                    cls_cache = cache_root / str(label)
                    cls_cache.mkdir(exist_ok=True)
                    crop_path = cls_cache / f"{img_path.stem}_{det_idx}.jpg"
                    crop.save(str(crop_path), quality=95)
                    self.samples.append((crop_path, label))
                else:
                    # keep in memory as tensor
                    t = transforms.ToTensor()(crop)
                    self.samples.append((t, label))
                n_matched += 1

        print(f"  [{split}] {n_matched} matched crops  "
              f"({n_skipped} images with no GT or no detections skipped)")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        src, label = self.samples[idx]
        if isinstance(src, Path):
            img = read_image(str(src)).float() / 255.0
            if img.shape[0] == 1:
                img = img.repeat(3,1,1)
        else:
            img = src  # already a tensor
        if self.transform:
            img = self.transform(img)
        return img, label


def _box_iou_np(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Compute IoU between two sets of xyxy boxes. Returns (N,M) matrix."""
    ax1,ay1,ax2,ay2 = a[:,0],a[:,1],a[:,2],a[:,3]
    bx1,by1,bx2,by2 = b[:,0],b[:,1],b[:,2],b[:,3]
    ix1 = np.maximum(ax1[:,None], bx1[None,:])
    iy1 = np.maximum(ay1[:,None], by1[None,:])
    ix2 = np.minimum(ax2[:,None], bx2[None,:])
    iy2 = np.minimum(ay2[:,None], by2[None,:])
    inter = np.maximum(0,ix2-ix1) * np.maximum(0,iy2-iy1)
    a_area = (ax2-ax1)*(ay2-ay1)
    b_area = (bx2-bx1)*(by2-by1)
    union  = a_area[:,None] + b_area[None,:] - inter
    return inter / (union + 1e-7)


# ─────────────────────────────────────────────────────────────────────────────
# GT-CROP DATASET  (original mode — loads crops generated by preprocess.py)
# ─────────────────────────────────────────────────────────────────────────────

class CropDataset(Dataset):
    """
    Loads 224×224 instance crops from
    processed/{split}/path_B/crops/{class_idx}/.
    """
    def __init__(self, crops_root: Path, split: str, transform=None):
        self.transform = transform
        self.samples   = []
        split_dir = crops_root / split / "path_B" / "crops"
        assert split_dir.exists(), f"Crops dir not found: {split_dir}"
        for cls_dir in sorted(split_dir.iterdir()):
            if not cls_dir.is_dir():
                continue
            try:
                cls_idx = int(cls_dir.name)
            except ValueError:
                continue
            for img_path in cls_dir.glob("*.jpg"):
                self.samples.append((img_path, cls_idx))
        print(f"  [{split}] {len(self.samples)} GT crops across {NUM_CLASSES} classes")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        img = read_image(str(img_path)).float() / 255.0
        if img.shape[0] == 1:
            img = img.repeat(3, 1, 1)
        if self.transform:
            img = self.transform(img)
        return img, label


def get_transforms(split: str):
    if split == "train":
        return transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomVerticalFlip(p=0.1),
            transforms.ColorJitter(
                brightness=0.3, contrast=0.3,
                saturation=0.3, hue=0.1,
            ),
            transforms.RandomRotation(30),
            transforms.Normalize(
                mean=[0.485, 0.456, 0.406],
                std =[0.229, 0.224, 0.225],
            ),
        ])
    return transforms.Compose([
        transforms.Normalize(
            mean=[0.485, 0.456, 0.406],
            std =[0.229, 0.224, 0.225],
        ),
    ])


def get_class_weights(crops_root: Path) -> torch.Tensor:
    weights_path = crops_root / "meta" / "class_weights.yaml"
    if not weights_path.exists():
        print("[warn] class_weights.yaml not found — using uniform weights")
        return torch.ones(NUM_CLASSES)
    with open(weights_path) as f:
        data = yaml.safe_load(f)
    cw = data.get("coarse_weights", {})
    weights = torch.tensor(
        [cw.get(cls, 1.0) for cls in COARSE_CLASSES], dtype=torch.float32)
    print(f"Class weights: "
          f"{ {c: round(float(w),3) for c,w in zip(COARSE_CLASSES, weights)} }")
    return weights


# ─────────────────────────────────────────────────────────────────────────────
# MODEL BUILDER
# ─────────────────────────────────────────────────────────────────────────────

def build_classifier(name: str) -> nn.Module:
    model_str, pretrained = CLASSIFIER_REGISTRY[name]
    model = timm.create_model(model_str, pretrained=pretrained,
                               num_classes=NUM_CLASSES)
    n = sum(p.numel() for p in model.parameters()) / 1e6
    print(f"  Built {name} ({model_str})  pretrained={pretrained}  {n:.1f}M params")
    return model


# ─────────────────────────────────────────────────────────────────────────────
# TRAINING LOOP
# ─────────────────────────────────────────────────────────────────────────────

def train_classifier(
    model, train_loader, val_loader,
    epochs, lr, device, class_weights, patience, output_dir,
) -> dict:
    model = model.to(device)
    class_weights = class_weights.to(device)

    criterion = nn.CrossEntropyLoss(weight=class_weights)
    optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=5e-4)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    best_val_acc = 0.0
    best_epoch   = 0
    no_improve   = 0
    history      = []

    weights_dir = output_dir / "weights"
    weights_dir.mkdir(parents=True, exist_ok=True)

    for epoch in range(1, epochs + 1):
        # ── train ─────────────────────────────────────────────────────────
        model.train()
        tr_loss = tr_correct = tr_total = 0
        for imgs, labels in tqdm(train_loader,
                                  desc=f"  Ep {epoch}/{epochs} train",
                                  leave=False):
            imgs, labels = imgs.to(device), labels.to(device)
            optimizer.zero_grad()
            out  = model(imgs)
            loss = criterion(out, labels)
            loss.backward()
            optimizer.step()
            tr_loss    += loss.item() * imgs.size(0)
            tr_correct += (out.argmax(1) == labels).sum().item()
            tr_total   += imgs.size(0)

        scheduler.step()
        tr_acc  = tr_correct / tr_total
        tr_loss = tr_loss    / tr_total

        # ── val ───────────────────────────────────────────────────────────
        model.eval()
        v_loss = v_correct = v_total = 0
        all_preds, all_labels = [], []
        with torch.no_grad():
            for imgs, labels in tqdm(val_loader,
                                      desc=f"  Ep {epoch}/{epochs} val",
                                      leave=False):
                imgs, labels = imgs.to(device), labels.to(device)
                out    = model(imgs)
                v_loss += criterion(out, labels).item() * imgs.size(0)
                preds   = out.argmax(1)
                v_correct += (preds == labels).sum().item()
                v_total   += imgs.size(0)
                all_preds.extend(preds.cpu().numpy())
                all_labels.extend(labels.cpu().numpy())

        v_acc  = v_correct / v_total
        v_loss = v_loss    / v_total
        v_f1   = f1_score(all_labels, all_preds,
                          labels=list(range(NUM_CLASSES)),
                          average="macro", zero_division=0)

        print(f"  Ep {epoch:3d}/{epochs} | "
              f"train loss={tr_loss:.4f} acc={tr_acc:.4f} | "
              f"val loss={v_loss:.4f} acc={v_acc:.4f} f1={v_f1:.4f}")

        history.append({
            "epoch": epoch,
            "train_loss": round(tr_loss,5), "train_acc": round(tr_acc,5),
            "val_loss":   round(v_loss,5),  "val_acc":   round(v_acc,5),
            "val_f1":     round(v_f1,5),
            "lr": round(scheduler.get_last_lr()[0], 8),
        })

        if v_acc > best_val_acc:
            best_val_acc = v_acc
            best_epoch   = epoch
            no_improve   = 0
            torch.save(model.state_dict(), weights_dir / "best.pt")
        else:
            no_improve += 1
            if no_improve >= patience:
                print(f"  Early stopping at epoch {epoch} "
                      f"(best epoch {best_epoch}, val_acc={best_val_acc:.4f})")
                break

    pd.DataFrame(history).to_csv(output_dir / "history.csv", index=False)
    return {
        "best_epoch":     best_epoch,
        "best_val_acc":   round(best_val_acc, 5),
        "stopped_early":  no_improve >= patience,
        "epochs_trained": epoch,
    }


# ─────────────────────────────────────────────────────────────────────────────
# TEST EVALUATION
# ─────────────────────────────────────────────────────────────────────────────

def evaluate_on_test(model, test_loader, device, output_dir, clf_name) -> dict:
    model.eval()
    all_preds, all_labels, all_probs = [], [], []
    with torch.no_grad():
        for imgs, labels in tqdm(test_loader, desc="  Test"):
            out   = model(imgs.to(device))
            probs = torch.softmax(out, dim=1)
            all_preds.extend(out.argmax(1).cpu().numpy())
            all_labels.extend(labels.numpy())
            all_probs.extend(probs.cpu().numpy())

    all_preds  = np.array(all_preds)
    all_labels = np.array(all_labels)
    all_probs  = np.array(all_probs)
    labels_r   = list(range(NUM_CLASSES))

    per_class_ap = {}
    for c in range(NUM_CLASSES):
        gt_bin = (all_labels == c).astype(int)
        per_class_ap[COARSE_CLASSES[c]] = (
            round(float(average_precision_score(gt_bin, all_probs[:, c])), 5)
            if gt_bin.sum() > 0 else 0.0
        )

    # latency
    dummy = torch.zeros(1, 3, CROP_SIZE, CROP_SIZE).to(device)
    for _ in range(10):
        model(dummy)
    t0 = time.perf_counter()
    for _ in range(100):
        model(dummy)
    lat_ms = (time.perf_counter() - t0) / 100 * 1000

    metrics = {
        "classifier": clf_name,
        "accuracy":   round(float((all_preds == all_labels).mean()), 5),
        "precision":  round(float(precision_score(all_labels, all_preds,
                             labels=labels_r, average="macro",
                             zero_division=0)), 5),
        "recall":     round(float(recall_score(all_labels, all_preds,
                             labels=labels_r, average="macro",
                             zero_division=0)), 5),
        "f1":         round(float(f1_score(all_labels, all_preds,
                             labels=labels_r, average="macro",
                             zero_division=0)), 5),
        "latency_ms": round(lat_ms, 3),
    }
    metrics.update({f"AP_{cls}": v for cls, v in per_class_ap.items()})

    # confusion matrix
    cm = confusion_matrix(all_labels, all_preds, labels=labels_r)
    fig, ax = plt.subplots(figsize=(10, 8))
    ConfusionMatrixDisplay(cm, display_labels=COARSE_CLASSES).plot(
        ax=ax, colorbar=True, xticks_rotation=45)
    ax.set_title(f"Path B — {clf_name} — test confusion matrix")
    plt.tight_layout()
    plt.savefig(output_dir / f"confusion_matrix_{clf_name}.png", dpi=150)
    plt.close()

    with open(output_dir / "metrics.json", "w") as f:
        json.dump(metrics, f, indent=2)

    print(f"\n  [{clf_name}]  accuracy={metrics['accuracy']:.4f}  "
          f"f1={metrics['f1']:.4f}  latency={lat_ms:.2f}ms")
    return metrics


# ─────────────────────────────────────────────────────────────────────────────
# SUMMARY
# ─────────────────────────────────────────────────────────────────────────────

def print_summary(output_dir: Path):
    records = []
    for p in sorted(output_dir.glob("*/metrics.json")):
        with open(p) as f:
            m = json.load(f)
        m["classifier"] = p.parent.name
        records.append(m)
    if not records:
        print("No metrics.json files found.")
        return
    df = pd.DataFrame(records).set_index("classifier")
    df = df.sort_values("accuracy", ascending=False)
    print("\n" + "="*70)
    print("PATH B  —  CLASSIFIER BENCHMARK SUMMARY")
    print("="*70)
    print(df.to_string(float_format="{:.4f}".format))
    print("="*70)


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser(description="Path B: two-stage detect+classify")
    p.add_argument("--detector_weights", type=Path, required=True,
                   help="best.pt from best Path A model (frozen detector)")
    p.add_argument("--crops_dir",        type=Path, required=True,
                   help="processed dataset root dir")
    p.add_argument("--output",           type=Path,
                   default=Path("runs/path_B"))
    p.add_argument("--classifiers",      nargs="+",
                   default=list(CLASSIFIER_REGISTRY.keys()),
                   choices=list(CLASSIFIER_REGISTRY.keys()))
    p.add_argument("--epochs",           type=int,   default=50)
    p.add_argument("--batch",            type=int,   default=32)
    p.add_argument("--lr",               type=float, default=1e-4)
    p.add_argument("--patience",         type=int,   default=10)
    p.add_argument("--device",           type=str,   default="0")
    p.add_argument("--mlflow_uri",       type=str,   default="./mlruns")
    p.add_argument("--summarize",        action="store_true")
    # ── YOLO-crop mode flags ───────────────────────────────────────────────
    p.add_argument("--use_yolo_crops",   action="store_true",
                   help="Extract crops from YOLO detector instead of GT crops")
    p.add_argument("--det_conf",         type=float, default=0.25,
                   help="YOLO detection confidence threshold for crop extraction")
    p.add_argument("--use_tta_wbf", action="store_true",
               help="Enable multi-scale TTA + WBF during YOLO crop extraction")
    p.add_argument("--tta_scales", nargs="+", type=int, default=[512, 640, 768],
                help="Scales used for TTA, e.g. --tta_scales 512 640 768")
    p.add_argument("--tta_flip", action="store_true",
                help="Also run horizontal flip in TTA")
    p.add_argument("--tta_wbf_iou", type=float, default=0.55,
                help="WBF IoU threshold for TTA fusion")
    p.add_argument("--tta_skip_box_thr", type=float, default=0.001,
                help="WBF skip_box_thr for TTA fusion")
    p.add_argument("--crop_cache_dir",   type=Path,  default=None,
                   help="Cache directory for YOLO-extracted crops")
    return p.parse_args()


if __name__ == "__main__":
    args = parse_args()

    if args.summarize:
        print_summary(args.output)
        raise SystemExit(0)

    device = torch.device(
        f"cuda:{args.device}" if torch.cuda.is_available() else "cpu")
    print(f"Device : {device}")
    if torch.cuda.is_available():
        dev = torch.cuda.get_device_properties(int(args.device))
        print(f"GPU    : {dev.name}  VRAM: {dev.total_memory/1e9:.1f}GB")

    mlflow.set_tracking_uri(args.mlflow_uri)
    class_weights = get_class_weights(args.crops_dir)
    args.output.mkdir(parents=True, exist_ok=True)

    # ── build datasets ────────────────────────────────────────────────────
    if args.use_yolo_crops:
        print("\n  Mode: YOLO on-the-fly crop extraction")
        print(f"  YOLO TTA+WBF: {args.use_tta_wbf}")
        if args.use_tta_wbf:
            print(f"  TTA scales: {args.tta_scales}")
            print(f"  TTA flip: {args.tta_flip}")
            print(f"  TTA WBF IoU: {args.tta_wbf_iou}")
            print(f"  TTA skip box thr: {args.tta_skip_box_thr}")
        from ultralytics import YOLO as _YOLO
        _detector = _YOLO(str(args.detector_weights))
        _det_dev  = args.device

        train_ds = YOLOCropDataset(
            args.crops_dir, "train",
            detector  = _detector,
            device    = _det_dev,
            conf      = args.det_conf,
            transform = get_transforms("train"),
            cache_dir = args.crop_cache_dir,
            use_tta_wbf     = args.use_tta_wbf,
            tta_scales      = args.tta_scales,
            tta_flip        = args.tta_flip,
            tta_wbf_iou     = args.tta_wbf_iou,
            tta_skip_box_thr= args.tta_skip_box_thr,
        )

        val_ds = YOLOCropDataset(
            args.crops_dir, "val",
            detector  = _detector,
            device    = _det_dev,
            conf      = args.det_conf,
            transform = get_transforms("val"),
            cache_dir = args.crop_cache_dir,
            use_tta_wbf     = args.use_tta_wbf,
            tta_scales      = args.tta_scales,
            tta_flip        = args.tta_flip,
            tta_wbf_iou     = args.tta_wbf_iou,
            tta_skip_box_thr= args.tta_skip_box_thr,
        )

        test_ds = YOLOCropDataset(
            args.crops_dir, "test",
            detector  = _detector,
            device    = _det_dev,
            conf      = args.det_conf,
            transform = get_transforms("test"),
            cache_dir = args.crop_cache_dir,
            use_tta_wbf     = args.use_tta_wbf,
            tta_scales      = args.tta_scales,
            tta_flip        = args.tta_flip,
            tta_wbf_iou     = args.tta_wbf_iou,
            tta_skip_box_thr= args.tta_skip_box_thr,
        )
    else:
        print("\n  Mode: loading pre-generated GT crops from disk")
        train_ds = CropDataset(args.crops_dir, "train",
                                transform=get_transforms("train"))
        val_ds   = CropDataset(args.crops_dir, "val",
                                transform=get_transforms("val"))
        test_ds  = CropDataset(args.crops_dir, "test",
                                transform=get_transforms("test"))

    train_loader = DataLoader(train_ds, batch_size=args.batch,
                              shuffle=True,  num_workers=4, pin_memory=True)
    val_loader   = DataLoader(val_ds,   batch_size=args.batch,
                              shuffle=False, num_workers=4, pin_memory=True)
    test_loader  = DataLoader(test_ds,  batch_size=args.batch,
                              shuffle=False, num_workers=4, pin_memory=True)

    all_metrics = {}

    for clf_name in args.classifiers:
        print(f"\n{'─'*60}")
        print(f"  Classifier : {clf_name}")
        print(f"{'─'*60}")

        run_dir = args.output / clf_name
        run_dir.mkdir(parents=True, exist_ok=True)

        model = build_classifier(clf_name)

        train_info = train_classifier(
            model=model, train_loader=train_loader,
            val_loader=val_loader, epochs=args.epochs,
            lr=args.lr, device=device,
            class_weights=class_weights, patience=args.patience,
            output_dir=run_dir,
        )

        # load best weights for test
        model.load_state_dict(
            torch.load(run_dir / "weights" / "best.pt", map_location=device))

        metrics = evaluate_on_test(
            model=model, test_loader=test_loader,
            device=device, output_dir=run_dir,
            clf_name=clf_name,
        )
        metrics.update(train_info)
        all_metrics[clf_name] = metrics

        mlflow.set_experiment("litter_path_B")
        with mlflow.start_run(run_name=clf_name):
            mlflow.log_params({
                "classifier":    clf_name,
                "epochs":        args.epochs,
                "batch":         args.batch,
                "lr":            args.lr,
                "patience":      args.patience,
                "use_yolo_crops":args.use_yolo_crops,
                "det_conf":      args.det_conf,
                "use_tta_wbf": args.use_tta_wbf,
                "tta_scales": str(args.tta_scales),
                "tta_flip": args.tta_flip,
                "tta_wbf_iou": args.tta_wbf_iou,
                "tta_skip_box_thr": args.tta_skip_box_thr,
                "device":        args.device,
            })
            mlflow.log_metrics({
                k: float(v)
                for k, v in metrics.items()
                if isinstance(v, (int, float)) and not isinstance(v, bool)
            })
            best_pt = run_dir / "weights" / "best.pt"
            if best_pt.exists():
                mlflow.log_artifact(str(best_pt), "weights")

        print(f"\n  [{clf_name}]  best_epoch={train_info['best_epoch']}  "
              f"val_acc={train_info['best_val_acc']:.4f}  "
              f"test_acc={metrics['accuracy']:.4f}  "
              f"f1={metrics['f1']:.4f}")

        del model
        torch.cuda.empty_cache()

    print_summary(args.output)
